### ISSUE TITLE
Submissions call does not contain viewingRestriction property to distinguish if an ontology is private or not

### ISSUE THREAD

**Issue by jonquet** [ncbo/ontologies_api#46]
The submissions call
http://data.bioontology.org/submissions?&display_links=false&display_context=false

does not contain the viewingRestriction field, thus there is no possibility to check if an ontology is private or not.

But the field shows up in the following call: 
http://data.bioontology.org/ontologies/NCIT?&display_links=false&display_context=false&display=all
But not in the following one: 
http://data.bioontology.org/ontologies/NCIT/latest_submission?&display_links=false&display_context=false&display=all

See also #45

**Comment by jvendetti** [comment]
This is by design. In BioPortal's model layer, [viewingRestriction is an attribute of the Ontology class](https://github.com/ncbo/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology.rb#L42), not the OntologySubmission class. 

This is not one of the attributes on the Ontology class that is surfaced by default. You need to use include parameters, e.g.:

http://data.bioontology.org/ontologies/NCIT?include=viewingRestriction

If you're iterating over a list of submissions, the JSON for each submission object contains the associated ontology acronym. You need to make a secondary API call to retrieve the ontology's viewingRestriction.

**Comment by jonquet** [comment]
Good. Ok thanks for the response. Indeed the Ontology object has 13 property fields so they might not all be included in the Submission.Ontology object.
